# Generated by Django 5.0.6 on 2024-06-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categroy',
            new_name='category',
        ),
    ]
